format = "$username $directory $git_branch $time\n  [󱞪](fg:light) "
palette = "winter-wonder"

[username]
disabled = false
format = "[](fg:charcoal)[ 󰧱 $user ]($style)[](fg:charcoal)"
show_always = true
style_root = "bg:charcoal fg:powder"
style_user = "bg:charcoal fg:powder"

[directory]
format = "[](fg:charcoal)[$path]($style)[](fg:charcoal)"
style = "bg:charcoal fg:powder"
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
format = "[](fg:charcoal)[ $symbol $branch ]($style)[](fg:charcoal)"
style = "bg:charcoal fg:frost"
symbol = ""

[time]
disabled = false
format = "[](fg:charcoal)[ $time 󰴈 ]($style)[](fg:charcoal)"
style = "bg:charcoal fg:mist"
time_format = "%I:%M%P"
use_12hr = true

[palettes.winter-wonder]
charcoal = '#1d252b'
slate = '#213955'
frost = '#445d88'
mist = '#aabadc'
powder = '#d6deee'
