format = "$username $directory $git_branch $time\n  [󱞪](fg:light) "
palette = "winter-wonder"

[username]
disabled = false
format = "[](fg:charcoal)[ 󰧱 $user ]($style)[](fg:charcoal)"
show_always = true
style_root = "bg:charcoal fg:cloud"
style_user = "bg:charcoal fg:cloud"

[directory]
format = "[](fg:charcoal)[$path]($style)[](fg:charcoal)"
style = "bg:charcoal fg:snow"
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
format = "[](fg:charcoal)[ $symbol $branch ]($style)[](fg:charcoal)"
style = "bg:charcoal fg:ice"
symbol = ""

[time]
disabled = false
format = "[](fg:charcoal)[ $time 󰴈 ]($style)[](fg:charcoal)"
style = "bg:charcoal fg:cloud"
time_format = "%I:%M%P"
use_12hr = true

[palettes.winter-wonder]
charcoal = '#313c45'
steel = '#4f6271'
ice = '#778ca4'
cloud = '#b3bfcb'
snow = '#d5dbe2'
